import db from "../../../utils/db";

/**
 * I DELEBERATELY separate the req and res type
 * It is autogenerated by typescript from inferring the codes
 */
interface ReqType {
  body: FirebaseFirestore.WithFieldValue<FirebaseFirestore.DocumentData>;
}
interface ResType {
  status: (arg0: number) => {
    (): any;
    new (): any;
    end: { (): void; new (): any };
    json: { (arg0: { id: string }): void; new (): any };
  };
}

export default async function EntryIndex(req: ReqType, res: ResType) {
  try {
    const { slug } = req.body;
    console.log("slug", slug);

    const entries = await db.collection("entries").get();
    const entriesData = entries.docs.map((entry) => entry.data());

    if (entriesData.some((entry) => entry.slug === slug)) {
      res.status(400).end();
    } else {
      const { id } = await db.collection("entries").add({
        ...req.body,
        created: new Date().toISOString(),
      });
      res.status(200).json({ id });
    }
  } catch (e) {
    res.status(400).end();
  }
}
